import type { PhraseExtra } from './phraseExtra';

export const MORE: PhraseExtra = {
  plain: {
    WANDER: [
      'My legs just filed an urgent ticket: “MOVE!”', 'Walking so hard the carpet will remember me!', 'If I stay seated one more second, I become furniture!',
      'Off on an EPIC journey to… the other side of the room!', 'The floor misses me. Tragic, really!', 'I shall pace like a lion in a very small savannah!',
      'Cardio? No. Lap of honour around my own cubicle!', 'Stretching! My spine sent a strongly worded email!', 'Breaking news: local human stands up, walks!',
      'My chair and I need space. It’s not you, it’s me!', 'Walking it out! Whatever “it” is. Probably Monday!', 'I’m sleepwalking, but make it professional!',
      'Quick, look purposeful! Nobody must know I have no destination!', 'Exploring the office like it’s a brand-new planet!', 'My step counter just gasped. First time today!',
      'Perimeter check! The coffee machine had better behave!', 'A dramatic stroll, to the sound of my own sighing!', 'Moving! The pedometer in my head demands it!',
      'Taking a walk before my brain turns to noodles!', 'Don’t mind me, just conducting a very serious inspection of nothing!', 'Every great idea started with a walk. Or a nap!',
      'Legs, you have ONE job. Go!', 'I’m taking the scenic route to absolutely nowhere!', 'Time to shake off this desk-shaped dent in my soul!',
    ],
    SOFA: [
      'The sofa waited ALL DAY for me. I can’t leave it hanging!', 'Collapsing onto the sofa with maximum drama!', 'My spine says “sofa” and my spine is never wrong!',
      'One tiny sit-down. The universe will not even notice!', 'I’m not tired, I’m just emotionally horizontal!', 'Sofa, take me away from this cruel world of tickets!',
      'Emergency cushion therapy! Stand back!', 'This is a medical necessity. I made up the doctor!', 'Plot twist: I sit down and never get up!',
      'The sofa and I are in a very committed relationship!', 'Resting my eyes. Just the eyes. And the rest of me!', 'My battery is at 1% and the sofa is my charger!',
      'Please hold all my calls. And my bugs!', 'I’m going to melt into the sofa like warm butter!', 'Everyone else is working, and I’m BRAVELY resting!',
      'The cushion remembers my shape. That’s love!', 'Boarding the sofa express! Next stop: snoozeville!', 'Time to be one with the upholstery!',
      'It’s a strategic retreat! Ask any general!', 'Nobody can find the bug if I’m under a blanket of silence!', 'Lowering myself onto the sofa. Gently. Heroically!',
      'This sofa has seen things. Now it will see me!',
    ],
    WINDOW: [
      'Gazing out like a sad poet in a rainy movie!', 'The window is basically a screen with zero ads!', 'Checking if the world is still out there. Spoiler: yes!',
      'I feel a deep, dramatic need for sunlight!', 'Staring at clouds. Rating them. This one is a 7!', 'Out there: freedom. In here: stand-up at 10!',
      'Window break! Because pixels are not the only things that glow!', 'Is that a pigeon? A very suspicious pigeon!', 'My eyes beg for a horizon!',
      'Sky status: still there! Great news for everyone!', 'I’m not slacking, I’m doing very deep scenery research!', 'Somewhere out there is a bug-free life. I’m looking for it!',
      'Watching the traffic like it’s the season finale!', 'Philosophical window time! Who am I? Why is it Tuesday?', 'The outside world has no merge conflicts!',
      'Pressing my forehead on the glass like a wistful puppy!', 'I wonder what the people down there are doing. Not tickets, surely!', 'Squinting at the sun like a tiny vampire!',
      'Look at that sky! It’s showing off again!', 'Pretending to think while I count passing cars!', 'The view is free and the Wi-Fi is not. Wins and losses!',
      'Window gazing: now with 100% more sighing!',
    ],
    PET: [
      'THE CAT IS RIGHT THERE. Everything else can wait!', 'My heart just did a backflip! Kitty!', 'Dropping everything for the fluffiest stakeholder!',
      'That purr is my favourite background noise!', 'I need to boop that nose IMMEDIATELY!', 'The cat looked at me. I felt it in my soul!',
      'Cat sighting! Code red! Code fluffy!', 'I will risk it all for a head scratch!', 'Whiskers detected! Productivity cancelled!',
      'The cat is clearly asking for me. Personally!', 'Warming up my hands for professional-grade petting!', 'If I don’t pet her, who will? The bugs?',
      'Little beans, little ears, big emergency!', 'Today’s only goal: make the cat purr!', 'Approaching slowly… the tail is up… we’re good!',
      'The cat is the real director here. I only report to her!', 'Fluff levels critical! Must investigate!', 'She’s loafing. I must see this loaf up close!',
      'Time to negotiate with the cat. I pay in scratches!', 'My stress level is dropping just looking at her paws!', 'One pet. Okay, forty. But who’s counting?',
      'Cat therapy session is open, and I’m first in line!',
    ],
    WATER: [
      'My throat is the Sahara! Send water!', 'Rescue mission to the cooler! Wish me luck!', 'Glug glug! The hero returns to the cooler!',
      'I am 70% water and 30% coffee, and the ratio is off!', 'Cold water! The champagne of the office!', 'The cooler bubbles! It’s calling me by name!',
      'Dehydrated and dramatic, the worst combo!', 'I’d cross a desert for this paper cup!', 'Gulp! One tiny cup, one giant relief!',
      'Splash of water, splash of hope!', 'The bubble in the cooler is my favourite show!', 'Refilling the tank! Pit stop, pit stop!',
      'Water break! Even my keyboard is thirsty for a rest!', 'My cup is empty. A tragedy in three acts!', 'Hydrating like my career depends on it!',
      'The cooler gossip is better than the Slack gossip!', 'Fresh cold water, like a tiny glacier in a cup!', 'My brain is a raisin. Must rehydrate!',
      'Off to drink the entire cooler! Or a cup. A cup!', 'Water: because deadlines are salty!',
    ],
    COFFEE: [
      'WITHOUT COFFEE I AM JUST A SLEEPY GOBLIN!', 'The machine hissed at me. That means come over, right?', 'Brewing is a sacred ritual and I am the priest!',
      'I can smell the beans from here. It’s a love story!', 'One cup, one miracle, repeat!', 'My veins demand a refill! Immediately!',
      'Coffee! The only thing that gets me through Mondays and Tuesdays!', 'Today’s motto: no cup, no clue!', 'I need a cup so strong it files its own pull requests!',
      'Pressing the button with the grace of a surgeon!', 'The gurgle of the machine is my favourite song!', 'Caffeine, my old friend, I’ve come to see you again!',
      'Coffee is just hug in a mug. Time for a hug!', 'I’m pretty sure my heartbeat is on a subscription plan with this machine!', 'Another cup? Like I even had a choice!',
      'Will the machine be kind to me today? Let’s see!', 'I’m a morning person. After the fourth cup!', 'The beans have spoken: it’s time!',
      'Who needs sleep when there’s a drip tray?', 'My soul hit “low battery”. Plugging into the espresso!', 'Hot, black and slightly scary, just like my backlog!',
    ],
    FISH: [
      'The fish have no tickets, no meetings, no mondays. Teach me!', 'Glub glub! The most relaxing show in the building!', 'I wonder if the orange one knows how beautiful it is!',
      'Watching the fish swim is basically free therapy!', 'The bubbles whisper their secrets to me!', 'Are they judging me? Probably. Politely!',
      'Fish don’t have deadlines. Fish have BUBBLES!', 'I’d like to be a fish for five minutes. Just five!', 'Look at them go! Swim, my friends, swim!',
      'A tiny underwater drama is unfolding. I need front-row seats!', 'The fish tank is my favourite streaming service!', 'Counting fins until my stress goes to zero!',
      'The little one is hiding again. Dramatic, just like me!', 'Blub blub! That’s my entire status update!', 'The water is calm, the fish are calm, I want to be calm!',
      'Time to check on the aquatic board of directors!', 'They float, I float, we all float in meaningless harmony!', 'Hello, my wet colleagues! Anything to report?',
      'Staring at fish like it’s the final episode!', 'The fish have an easy life. I will watch it for them!', 'The filter hums, the fish glide, my soul heals!',
      'Dinner theatre for people who forgot dinner: the fish tank!',
    ],
    WASH: [
      'A glorious splash to revive this tired soul!', 'Cold water, hot takes, fresh face!', 'My face has seen too many screens. Rinse time!',
      'Face wash! Today’s tiny spa day!', 'I’m going to splash myself back to life!', 'The sink and I have a date. It’s serious!',
      'Dramatic splashing in 3, 2, 1!', 'Wiping away the stress, one droplet at a time!', 'I can’t go on like this! To the faucet!',
      'Sink time! Please, bring a towel!', 'Rinsing off the debugging fog!', 'Water, restore my youth! Or at least my eyes!',
      'My face has gone full zombie, emergency splash!', 'Splish splash, I’m taking a bath. A very small one!', 'Time to look alive for the afternoon! Or try!',
      'The tap is my magic fountain!', 'Cold water therapy: 10/10 would splash again!', 'Looking fresh is a lie I can fix with soap!',
      'This sink has all the answers. And water!', 'The towel is waiting for me. Don’t keep it waiting!',
    ],
    PLANTS: [
      'The poor plants are practically screaming! Water incoming!', 'Rain, but make it a watering can!', 'My leafy friends, your hero is here!',
      'If they droop another millimetre, I’ll cry!', 'Time to be a gardener. Gloves optional!', 'Glug, glug, little roots! Drink up!',
      'The cactus says “no”. The ferns say “please”. Fine!', 'Nobody waters like I water! Nobody!', 'Feeding the greenery! The circle of life!',
      'Photosynthesis, take it away!', 'I’m basically the sun with a tiny jug!', 'These plants are my children. Thirsty children!',
      'A drop for you, a drop for you, a drop for everyone!', 'Look at those leaves! Such drama! Such thirst!', 'I promised the plants I’d come. A promise is a promise!',
      'Every plant deserves a spa day. Doors open now!', 'The soil is dry as a bone, a dusty tragedy!', 'Time to turn this office into a jungle! A wet one!',
      'Sprinkle sprinkle! Grow, my beauties, GROW!', 'The little green guys are staring at me. Guilt!', 'Leafy emergency! Pouring now!',
      'The best code I’ve written this week is a watering schedule!',
    ],
    COOK: [
      'MY STOMACH JUST WROTE A LEGAL COMPLAINT!', 'Boil, bubble, slurp! The noodle ritual begins!', 'The stove awaits its master chef! Me! Hello!',
      'Today’s menu: noodles. Tomorrow’s menu: also noodles!', 'I’m going to cook the greatest noodle bowl in history!', 'Heat on, brain off, flavour max!',
      'Cooking time! Please clear the kitchen of all critics!', 'Water, noodles, destiny!', 'I smell victory. It smells like broth!',
      'A grand culinary adventure of three ingredients!', 'Feeding the beast inside! It’s very loud!', 'Hunger level: eating a keyboard!',
      'My noodle skills are legendary. Mostly because I have no others!', 'To the stove! Whatever happens, I blame the salt!', 'Starving! Dramatically! Theatrically! Noodle-ly!',
      'Boiling water is basically alchemy. Let me turn it into lunch!', 'The pot is calling me, and the pot never lies!', 'The only thing hotter than this stove is my hunger!',
      'Chef Noodle reporting to the kitchen!', 'Please stand back, genius at work!', 'A little chili, a little hope, and bon appétit!',
      'Dinner is coming! Eventually! Probably! Hopefully!', 'If I don’t eat now, I’ll turn into a grumpy ghost!', 'Slurp preparations underway! The kitchen is mine!',
    ],
    BOX: [
      'Bag, prepare yourself, a Monday is coming!', 'Time to give that dummy a piece of my mind! In punches!', 'Every stressful sprint ends in a left hook!',
      'I name this dummy: “Merge Conflict”!', 'Let me out! The fists want out!', 'Round one: me versus all my problems!',
      'This dummy has never complained once. Excellent listener!', 'POW! That one was for the deadline!', 'Boxing gloves on, anxiety off!',
      'I’m a lover, not a fighter. But also, boxing!', 'Prepare for the most dramatic jab you’ve ever seen!', 'KO the stress! TKO the to-do list!',
      'The dummy knows what it did!', 'Cracking my knuckles! Warning: it’s just a vibe!', 'Fists of fury! Fists of mild irritation, actually!',
      'I’ve got a lot of feelings and one dummy!', 'The bell rings! My patience does not!', 'Let me punch out this headache!',
      'Dodging, weaving, and probably tripping!', 'The big fight! Me against the sandbag! It’s a classic!', 'Whack! Smack! Back to code!',
      'This is therapy, but with extra thumps!',
    ],
    LIFT: [
      'The dumbbells are begging for a rematch!', 'Lifting these will change my life! Or my biceps, at least!', 'Look at me! I’m basically a bodybuilder! In spirit!',
      'Flexing in front of the plants!', 'Reps for the ‘gram! Nobody’s watching, but still!', 'Muscles, awake! The keyboard has weakened you!',
      'I lift heavy things so I don’t cry at heavy tickets!', 'These weights and I have a very toxic relationship!', 'Every curl is a tiny victory!',
      'My arms can lift a bug report, that counts!', 'Time to become a legend! Slowly, with a lot of grunting!', 'ONE MORE REP! That’s what I tell myself!',
      'The iron calls, and I answer in whimpers!', 'Pumping up! Mainly the volume of my sighs!', 'Strongest developer in the building! Ask no one!',
      'I shall lift until my coffee gets cold!', 'Beast mode: initialised! Also tired!', 'Arms like cables, but heavier!',
      'Get ready for the most dramatic grunting of your life!', 'Biceps, report for duty! Triceps, you too!', 'Lifting! Because typing builds only my thumbs!',
      'Lifting weights so I can lift my spirits! And the box!',
    ],
    LOUNGE: [
      'The bean bag swallowed me last time. I’m going back for more!', 'Flopping down like a dropped sack of potatoes!', 'Bean bag: my kingdom, my throne!',
      'Gravity wins again, and I let it!', 'Sinking into the beans with dignity! Mostly!', 'This is how champions rest: flat and fluffy!',
      'I’m the cat now. Look at me lounge!', 'Beans, take me! Please! Gently!', 'My bones are made of bean bag filling now!',
      'The most comfortable collapse of my day!', 'I call this: “professional horizontal thinking”!', 'Don’t wake me. Unless there’s snacks!',
      'Lowering into the bean bag like a very slow elevator!', 'Look at that squish! I must be part of it!', 'Soft, squishy, and ever so judgey: the bean bag!',
      'Ceiling, you and I have much to discuss!',
    ],
    SLEEP: [
      'The nap I’ve dreamed of all day, finally!', 'I’m closing my eyes. For research!', 'Sleeping is my cardio, and I’m very fit!',
      'Eyelids are closing with a mind of their own!', 'Don’t wake me unless the building is on fire! A small fire!', 'Powering down! Please stand by!',
      'One hundred percent exhausted, zero percent ashamed!', 'Dream of a world with no stand-ups…', 'Napping like a champion who has run out of coffee!',
      'Please leave a message after the snore!', 'The pillow in my mind is calling me!', 'Sleep mode: engaged! Dreams: loading!',
      'It’s not slacking, it’s “strategic unconsciousness”!', 'If the boss asks, I’m in a very deep meeting. With my eyelids!', 'Good night, world! It’s only the afternoon!',
    ],
    SMOKE: [
      'Just popping out for “fresh air”. Mostly the air part!', 'Five minutes at the window! The excuse of the century!', 'I need a little drama by the window. And air!',
      'Stepping out to stare at the sky for a bit!', 'Taking a very serious “air quality inspection”!', 'The window and I have things to discuss. Alone!',
      'A quick break to rethink my life. Or the deadline!', 'I’ll be back before the kettle boils! Maybe!', 'Time for a tiny pause. Nobody get dramatic!',
      'Gone for a moment of quiet! Back when the quiet is over!',
    ],
  },
  named: {
    WATCH: [
      '{n} is typing like the keyboard owes them money!', 'Look at {n} go! It’s like watching a movie!', '{n} has the focus of a hawk! A hawk with coffee!',
      'I must witness {n}’s genius at close range!', 'Is {n} coding or conducting an orchestra?', '{n} is fast! Does the keyboard hurt?',
      'Popcorn! I’m going to watch {n} work!', 'Spying on {n}. In a friendly, supportive way!', '{n}’s screen is a scroll of mysteries! I’m going in!',
      '{n} is in the zone. I’ll watch from the edge of the zone!', 'Let me learn from the master, {n}!', 'The legend {n} is at work! Gather round!',
      'Whoa, {n}’s monitor is blinking. Something is going on!', 'If {n} sneezes, I’ll catch the bug first!', 'My favourite show: “{n} Fixes Everything”!',
      'I want to see {n} slay that bug live!', '{n} frowns, {n} types, I clap! That’s the plan!', 'Breathless, I approach {n}’s desk!',
    ],
    CHAT: [
      'I must tell {n} about my terrible Monday!', '{n} and I have unfinished gossip!', 'Time for a dramatic chat with {n}! Stand back!',
      'I’ll go bother {n} for exactly two minutes. Or twenty!', 'Surely {n} wants to hear about my noodles!', '{n} looks lonely. Fix incoming: me!',
      'Off to share my deepest sighs with {n}!', 'I have a shocking announcement for {n}! It’s about lunch!', '{n} and I are overdue a heart-to-heart!',
      'Let me spread chaos at {n}’s desk!', 'Must get {n}’s opinion about my very important sandwich!', 'I’m going to confuse {n} with my theories!',
      'The social battery is at 4%. {n} shall have it all!', 'Time to ruin {n}’s focus. Lovingly!', 'I’ll ask {n} if they saw the cat. They always did!',
      '{n}, I come bearing questions and zero solutions!', 'Whispering sweet nothings to {n}: “Is it Friday yet?”', '{n} is my favourite distraction today!',
    ],
  },
  read: [
    'Brave soul time: opening “{b}”!', 'Dramatic page-turning of “{b}” begins now!', '“{b}”! I’ve heard it changes lives. Or naps!',
    'I’ll read “{b}” faster than a compile on a good day!', 'Dusting off “{b}” like an ancient treasure!', 'Page one of “{b}”! The suspense is killing me!',
    '“{b}” and me: a love story in four hundred pages!', 'Let me devour “{b}” in a single gulp!', 'The plot of “{b}” is probably exactly my life!',
    'I’ll sniff the pages of “{b}”. That’s half the joy!', 'Sit down, “{b}”, we’re finally doing this!', 'If “{b}” has a twist, I’ll scream!',
    'Reading “{b}” while pretending not to be sleepy!', '“{b}” is calling. In a very quiet, bookish voice!', 'Time to get lost in “{b}” for a moment!',
    'I’ve read the first chapter of “{b}” ten times. This is the eleventh!', 'Adventure awaits inside “{b}”! Or at least coffee stains!', 'I’m about to be the smartest person here, thanks to “{b}”!',
  ],
};
