import type { PhraseExtra } from './phraseExtra';

export const MORE: PhraseExtra = {
  plain: {
    PHONE: [
      'BREAKING: my thumb has declared independence 📱', 'I am NOT addicted, I can stop… right after this reel 📱', 'The phone whispered my name. I had no choice! 📱',
      'Sitting down for a scroll of EPIC proportions 📱', 'My feed has missed me terribly, I can feel it 📱', 'Fifteen seconds. Okay, fifteen minutes. Okay, forever 📱',
      'The algorithm and I have a date 📱', 'Hold my calls, the memes are urgent 📱', 'Doomscrolling like it’s an Olympic sport 📱',
      'One tiny peek turns into a three-hour journey 📱', 'The group chat is on FIRE and I must witness it 📱', 'Fear of missing out? More like fear of MISSING EVERYTHING 📱',
      'Scrolling so hard my chair is getting dizzy 📱', 'Me and my phone, a love story in 4K 📱', 'This is not procrastination, it is competitive scrolling 📱',
      'Charging my social battery by draining the real one 📱', 'Sit. Scroll. Regret. Repeat. 📱', 'Gasp! A notification! Or a ghost. Checking 📱',
      'Professional thumb workout, don’t disturb 📱', 'Reading the comments. Why do I do this to myself? 📱',
    ],
    WC_HURRY: [
      'MOVE! Code red, code brown… I mean code yellow!', 'I would run faster but then I would… never mind, GO!', 'Tell my family I loved them – restroom first!',
      'It’s a race against time and I’m LOSING!', 'Clear the hallway! Precious cargo!', 'Three coffees. One bladder. ZERO mercy!',
      'Hold the elevator! Wrong room, hold the DOOR!', 'My bladder filed an emergency ticket!', 'Out of my way, I have a date with destiny!',
      'Sprinting like the build depends on it!', 'Not now, deadlines! Nature outranks you!',
    ],
    WC_PLAIN: [
      'Off to the porcelain palace', 'A short visit to the throne room', 'The little room calls', 'Be right back, don’t touch my chair!',
      'Gone for a short while, hold my seat', 'Time for a tiny holiday in the restroom', 'Visiting the smallest room, with the biggest relief', 'Excuse me, I have an important appointment',
    ],
    WC_PHONE: [
      'The throne has Wi-Fi, who knew? 📱', 'Phone in hand, I’m ready for the long haul 📱', 'The best scrolling happens in there, ask anyone 📱',
      'See you in half an hour, I have reels to watch 📱', 'My office away from the office 📱', 'A grand tour of my feed, sitting down 📱',
      'Don’t wait up, I’m going on a scroll expedition 📱', 'The restroom: now with premium entertainment 📱',
    ],
    WC_BOOK: [
      'Off to read a whole novel in the smallest room', 'Chapter twelve awaits on the throne', 'Taking my book to the quietest library in town',
      'A literary retreat, door closed', 'Bringing Shakespeare to the porcelain stage', 'Book club, population one, location restroom',
      'I’ll finish this book if it takes all day!', 'The plot thickens… in there',
    ],
    WC_NONE: [
      'Just me, my thoughts and a locked door', 'No phone, no book, pure meditation', 'Going to stare at the tiles like a philosopher', 'Back soon, I’m going analogue!',
      'A digital detox, thirty seconds long', 'Alone with the tiles, as nature intended', 'No gadgets, just vibes', 'The quietest meeting room in the building',
    ],
    WASH_HANDS: [
      'Scrubbing like a surgeon about to save the world!', 'Soap, water, victory!', 'Squeaky clean, like a brand new commit', 'Twenty seconds, no cheating!',
      'These hands are CLEAN, certified, stamped!', 'Hand wash! Like a professional bubble artist', 'Hygiene hero reporting for duty', 'Lather, rinse, be proud of me',
      'Spotless! You could eat noodles off these hands. Don’t.', 'The sink and I have a close relationship',
    ],
    TABLE_COFFEE: [
      'Sit down, coffee up, world off!', 'A coffee summit at the round table!', 'This cup deserves a proper chair', 'Table, coffee, zero stress. Heaven!',
      'Round table, round of coffee, round of gossip?', 'I’m holding a board meeting. Board: me, coffee.', 'Coffee break, now with extra dignity',
      'Anyone who talks to me before the last sip is in trouble!', 'The table is calling, with a mug in its hand', 'Coffee at the table: luxury edition!',
      'I will sip this slowly, like a king!',
    ],
    TABLE_MEAL: [
      'Lunch time! Everybody stop being productive!', 'A feast fit for a developer at the round table!', 'Table, fork, bowl: let the banquet begin!',
      'Eating at a table? Who do I think I am, a CEO?', 'This meal gets a seat of honour!', 'Dining like royalty, one noodle at a time',
      'Nobody touch my bowl, I’ve been dreaming of this since 9 a.m.!', 'The round table becomes a restaurant. Reservation: me.', 'Bon appétit, me, you magnificent diner!',
      'Time to eat like nobody’s watching. Everybody’s watching.', 'Lunch break! Get the good chair!',
    ],
    UNBOXED_ANY: [
      'It’s… something! Something GLORIOUS!', 'Whatever this is, it’s the best day of my life!', 'The box was big, the mystery bigger!', 'Is it a gift? A miracle? A mistake? I love it!',
      'Better than Christmas, I swear!', 'Ta-daaa! I have no idea what that is!', 'Open, gasp, applaud, repeat!', 'This is why I work here!',
    ],
    FETCH_COFFEE: [
      'Coffee quest, accept! Going in!', 'I must have coffee or I will turn to dust!', 'Off to slay the coffee machine!', 'Bring me the BEANS!',
      'A hero walks to the coffee machine!', 'Refuelling the human engine!', 'My cup is empty and so is my soul!', 'Brewing happiness, one cup at a time!',
      'Rushing to the coffee machine like it’s Black Friday!', 'Nothing can stop me from this cup!', 'Coffee, my one true love, I’m coming!',
    ],
    FETCH_MEAL: [
      'FOOD! I must find FOOD!', 'My stomach is writing a strongly worded letter!', 'To the fridge, brave soldier!', 'Leftovers, my leftovers, where are you?!',
      'I’m so hungry I could eat the keyboard!', 'Raid the fridge! Take no prisoners!', 'Lunch, my sweet lunch, I’m coming!', 'The fridge light is my lighthouse!',
      'Hungry mode: DANGEROUS. Stand back!', 'Operation Snack is a go!', 'If the yoghurt is still there, I will cry with joy!',
    ],
    CARRY_DESK: [
      'Back to my desk, cup first, dignity second', 'Desk, my loyal friend, I bring you gifts!', 'Walking slowly so nothing spills. Eyes on the cup!',
      'The desk gets the best cup in the building!', 'One careful step at a time, nobody bump me!',
    ],
    CARRY_TABLE: [
      'The round table awaits its king!', 'A grand procession to the round table!', 'Nobody sit in my spot at the table!', 'Careful, careful, to the table!',
      'The table is my stage and this is my prop!',
    ],
    CARRY_SOFA: [
      'The sofa will never see this coming!', 'Plan: sofa, cup, bliss. Execute!', 'Sneaking this to the sofa like a secret agent', 'Soft cushions, here comes the cargo!',
      'The sofa deserves the best, and so do I!',
    ],
    SERVE: [
      'TA-DAA! Behold the noodle masterpiece!', 'Steaming hot and unbelievably beautiful!', 'Gordon Ramsay would weep with joy!', 'Dinner is served, bow before the bowl!',
      'The noodles have achieved perfection!', 'Eat it while it screams “delicious”!', 'I am the noodle whisperer!', 'A culinary miracle, right here!',
      'Don’t look at me, look at this masterpiece!', 'Plated like a pro, burned like… not at all!', 'Seven stars! Maybe eight!', 'Noodles, now with 100% more drama!',
      'Chef’s kiss to myself!', 'Fresh from the heavens (the stove)!', 'Hot hot hot, but SO worth it!', 'Come and get it before I eat it myself!',
    ],
    EAT: [
      'OH MY GOODNESS, this is the best noodle I’ve ever had!', 'I’m crying. Happy noodle tears.', 'Somebody call the food critics!', 'Food coma incoming, and I welcome it!',
      'One bite and I forgot all my bugs!', 'This bowl contains the secrets of the universe', 'Slurp so loud the cat looked up!', 'I would fight a dragon for this bowl',
      'Heaven exists, and it is hot and salty!', 'Nom nom nom, don’t talk to me!', 'My taste buds are throwing a party!', 'Never share food, my one rule!',
      'Compliments to the chef. I am the chef. Thanks!', 'I could eat ten of these. Don’t test me!', 'This is what peak performance tastes like!', 'My mum would be so proud of this bowl',
      'I have achieved noodle enlightenment', 'Chopsticks: 1. Hunger: 0.', 'Somebody hold me, this is TOO good!', 'Spicy! Tears! Joy! All three!',
      'Bowl, you complete me!', 'Careful, I’m in a relationship with this meal',
    ],
    TABLE_LINES: [
      'Honestly, who invented Mondays? I want a word!', 'I’m convinced the cat runs this office!', 'Did you see my last commit? Poetry. Pure poetry!', 'I laughed so hard I scared the plant!',
      'You won’t believe what just happened at my desk!', 'Is it just me or is the coffee getting stronger every day?', 'This table has seen things. Terrible, wonderful things.',
      'I swear the fridge ate my sandwich!', 'If I ever win the lottery, I’m buying this table!', 'You’re telling me the printer works now? LIES!',
      'My chair squeaks, and I think it’s judging me!', 'I just remembered something so embarrassing!', 'Quick, someone say something smart, the boss is passing!',
      'On a scale of one to cat, how tired are you?', 'That’s the funniest thing I’ve heard all week, and I heard a lot!', 'No no no, you’re doing it wrong, give me that mug!',
      'I vote that this table gets a raise!', 'What’s the weirdest thing you ever found in a codebase?', 'I was going to say something clever but I forgot!',
      'Is this a meeting? Can I leave? Kidding, I’m staying!', 'If bugs paid rent, I’d be rich!', 'Do you ever look at the fish and just… feel things?',
      'My horoscope said “today you will drink coffee”. Wow!', 'Dramatic pause… okay, I forgot what I was saying!', 'I told the plant a secret. Now it knows too much!',
      'Everybody pretend to talk about work, here comes the director!', 'Whoever invented noodles deserves a statue!', 'That story just got ten times better!',
      'I can’t feel my legs. Oh wait, it’s just the sofa!', 'Do you think the cat has her own desk somewhere?', 'Quick poll: who’s actually working right now?',
      'I’d trade my keyboard for a nap, no questions asked!', 'This is the most productive non-work I’ve ever done!', 'Wait, you’ve never tried pineapple on noodles?!',
      'Tell me the truth: did you steal my pen?', 'Plot twist: it was the intern all along!', 'My biggest talent is looking busy. Watch this!',
      'Careful with that mug, it’s older than the company!', 'Okay, I’m sold, count me in!', 'Excuse me, this is a no-work zone!',
      'The best ideas come with biscuits!', 'No way! Say that again, slowly!', 'I’m not gossiping, I’m exchanging information!',
      'Who else misses the sofa already?', 'What’s a good excuse to stay here till Friday?', 'This is better than any team-building day!',
      'You’re so right it hurts!', 'Not me crying over a cold noodle!', 'Hold on, let me take a bow for that joke!', 'The fish are watching. They always are.',
    ],
  },
  scrollTargets: [
    ['a video of a cat losing to a cucumber', '🥒'], ['a goat screaming in perfect pitch', '🐐'], ['a dramatic video of a toddler negotiating', '👶'],
    ['a tutorial for making toast in 47 steps', '🍞'], ['an influencer eating one noodle for ten minutes', '🍜'], ['a penguin falling over in slow motion', '🐧'],
    ['a pet that thinks it’s a person', '🐕'], ['the most dramatic weather forecast ever', '🌪️'], ['a conspiracy theory about pigeons', '🕊️'],
    ['a guy who reviews every sandwich in town', '🥪'], ['an unboxing of a rock', '🪨'], ['a sunset filmed in 12 different filters', '🌅'],
    ['a speedrun of folding laundry', '👕'], ['a quiz that guesses my age wrong', '🎂'], ['a celebrity chef yelling at an egg', '🍳'],
    ['my ex’s very happy vacation photos', '🏝️'], ['a tiny house with a huge dog', '🏡'], ['how to survive a zombie apocalypse in a cubicle', '🧟'],
    ['an exploding watermelon experiment', '🍉'], ['a hamster eating a very small burrito', '🌯'], ['a hot take about pineapple on pizza', '🍕'],
    ['a baby panda sneezing', '🐼'], ['the world’s longest cat video', '🐈'], ['a man who judges strangers’ sneakers', '👟'],
    ['my screen time report of shame', '📊'], ['a tutorial for tying shoelaces differently', '👞'], ['somebody’s 5 a.m. routine', '🌄'],
    ['a street dancer who ruined my afternoon', '🕺'], ['a bridge falling over in a video game', '🌉'], ['a talking parrot arguing with its owner', '🦜'],
    ['an expert explaining why my plant is sad', '🪴'], ['a goat on a roof for no reason', '🏠'], ['a 3 a.m. thought somebody posted', '🌙'],
    ['a mystery that turned out to be a sock', '🧦'], ['a dramatic reading of a grocery list', '🛒'], ['the world’s angriest duck', '🦆'],
    ['a prank where somebody wrapped everything in foil', '🪩'], ['a lighthouse keeper’s lunch', '🥣'], ['a chair that does yoga', '🧘'],
    ['an octopus escaping from a jar', '🐙'], ['a cursed recipe for blue soup', '🥣'], ['the rumour that Friday is cancelled', '📅'],
    ['a raccoon doing laundry', '🦝'], ['a ranking of every kind of cheese', '🧀'], ['a talent show for houseplants', '🌿'],
    ['a dramatic cooking show for toast', '🍞'], ['someone explaining a meme I’m too old for', '👴'], ['a snail winning a tiny race', '🐌'],
    ['a video of a robot vacuum fighting a sock', '🤖'], ['a shopping haul of 40 identical mugs', '☕'], ['the horoscope for cats', '🐱'],
    ['a cooking disaster in perfect slow motion', '🔥'], ['an epic fail compilation of office chairs', '💺'],
  ],
  scrollOpeners: [
    'Emergency! I MUST see {x}', 'THE WORLD NEEDS ME to check {x}', 'I have been waiting my whole life for {x}', 'Drop everything, it’s time for {x}!',
    'I swear {x} is calling me right now', 'If I don’t see {x} immediately, I will explode', 'Sorry, work, I have a prior engagement with {x}',
    'Shhh! Nobody speak, I’m going to {x}', 'Oh, I’ve heard about {x}. Let me see!', 'Don’t judge me, I need {x} for my sanity',
    'My brain cannot continue without {x}', 'It’s been five whole minutes since I checked {x}!', 'Plot twist: I’m actually here for {x}',
    'I have a really good feeling about {x}', 'The gossip says {x} is MASSIVE today', 'This is serious business: {x}',
    'I’m ready, I’m braced, show me {x}!', 'Somebody sent me {x} and I’m dying to look', 'Breaking: I have found {x}!', 'Just once more, I need {x}',
  ],
  scrollFull: [
    ['I scrolled for an hour and learned absolutely nothing!', '🧠'], ['Somebody liked my post! A real person! Probably!', '❤️'],
    ['Why does every video end at the best part?!', '😤'], ['I’m 100% sure this phone is listening to me', '👂'],
    ['Gasp! My ex finally got a haircut!', '💇'], ['One more scroll and I’ll stand up. Promise.', '🤞'],
    ['The battery drops faster than my motivation', '🔋'], ['This feed knows me better than my mum', '🫣'],
    ['I just watched a cat do my job better than me', '🐈'], ['Everybody is on holiday except me. Rude.', '🏖️'],
    ['Wait, is that a sale?! I must see it!', '🏷️'], ['I’ve been scrolling so long I forgot my own name', '🌀'],
    ['Pretending to read an important email', '✉️'], ['They said never to look at the comments. I looked.', '💬'],
    ['New phone, who dis? Oh, it’s still mine.', '📲'], ['My thumb deserves a gold medal', '🥇'],
  ],
  unboxed: [
    '{N}?! Who approved this budget? I love it!', '{N}! The office just levelled up!', 'THIS is {n}?! Unreal!', 'We ordered {n}, and it actually arrived! Miracle!',
    '{N}, you magnificent thing!', 'Ladies and gentlemen: {n}!', 'Gasp! {N}! My dreams came true!', 'I knew it was {n}! I always knew!',
    'Somebody pinch me, it’s {n}!', 'The cat has already claimed {n}', 'Is that really {n}? I need a minute!',
  ],
};
