import type { PhraseExtra } from './phraseExtra';

export const MORE: PhraseExtra = {
  plain: {
    OPEN_MORNING: [
      'Rise and shine, desk! Your hero has arrived!', 'The sun is up, the coffee is calling – I answer!', 'Morning! I fear nothing but an empty mug!',
      'Dawn breaks, and so does my sleep schedule!', 'Behold! The first human of the day!', 'Good morning, chairs! Did you miss me terribly?',
      'Who needs sleep? Me. But here I am!', 'Mornings are a scam, yet here we are, smiling!', 'The birds are singing! Somebody make them stop!',
      'Opening the office before the sun finishes yawning!', 'Another glorious morning of questionable decisions!',
    ],
    OPEN_AFTERNOON: [
      'Afternoon already?! The morning vanished without a trace!', 'Lunch is a memory, the grind is eternal!', 'The office awaits its legend, a bit late!',
      'Opening up at noon-ish! Call it a bold strategy!', 'Behold, the post-lunch hero arrives!', 'Empty office, full of destiny!',
      'The afternoon slump is coming and I’m not ready!', 'Doors open! Dramatic music, please!', 'Hello, silence! You’ve been a lovely tenant!',
      'Half the day is gone, so I’ll work twice as dramatically!',
    ],
    OPEN_EVENING: [
      'The sun has fled, but I, I stay!', 'Night shift! Cue the heroic violins!', 'Opening at night like a very tired vampire!',
      'Who works when the moon is out? This guy!', 'The office is dark, my spirit is brighter!', 'Evening already?! Time is a thief!',
      'Lights on! Let the midnight madness begin!', 'Just me, the lamps and my terrible ideas!', 'Everyone went home, but my laptop called me back!',
      'Dinner can wait, the code cannot!',
    ],
    OPEN_ANY: [
      'The empty office trembles at my arrival!', 'Doors open! Fate begins to type!', 'Alone at last! Nobody to judge my snack!',
      'The throne room is open for business!', 'Silence? Not for long, I have a keyboard!', 'Attention, furniture! The boss is in!',
      'Let the great adventure of tiny tasks begin!', 'Warming up the chair – it’s a sacred ritual!', 'Hello, plants! Did anyone water you? Not me!',
      'The whole building is mine! Nobody tell the cat!', 'I flip the switch and the world begins again!', 'Today’s mission: survive. Bonus: ship!',
    ],
    HELLO_DIRECTOR: [
      'Oh! You’re all here?! Nobody told me I was late!', 'Team! My loyal, slightly sleepy team!', 'Behold! The boss has arrived, applause optional!',
      'Hello, my wonderful, caffeinated minions!', 'Look at you all, working so hard! Suspicious!', 'Did anyone touch my chair? Be honest!',
      'I came, I saw, I’m already behind!', 'Hello, team! Please act busy, I’m watching!', 'Back in the building! Hide the snacks!',
      'What did I miss? A fire? A promotion? A cat?', 'Good to see everyone! Mostly. Kidding! Mostly!',
    ],
    BOSS_MORNING: [
      'Morning, boss! You look radiant! Or tired. One of those!', 'Good morning, boss! I brought nothing but loyalty!', 'Boss! You beat the sun again!',
      'Morning, boss! Please be in a good mood!', 'Hail the early boss! Is there coffee left?', 'Boss, morning! I was dreaming of tickets!',
      'Good morning, boss! My brain is still in bed!', 'Morning! Do I get a medal for showing up?', 'Boss! Bright and early! Who hurt you?',
      'A wonderful morning, boss! Said nobody ever, but still!',
    ],
    BOSS_AFTERNOON: [
      'Afternoon, boss! I got lost in a very long lunch!', 'Boss! I’m here! The traffic was biblical!', 'Good afternoon, boss! Please don’t check the clock!',
      'I’m late, boss, but my enthusiasm is on time!', 'Afternoon, boss! Tell me nothing is on fire!', 'Boss! I was held up by a sandwich of destiny!',
      'Afternoon, boss! I come bearing excuses!', 'Boss! Did the office survive without me? Be kind!', 'Good afternoon! I have fully recovered from lunch!',
      'Hello, boss! I’m here to save the afternoon!',
    ],
    BOSS_EVENING: [
      'Evening, boss! You live here now, don’t you?', 'Boss! Still here?! Do you ever sleep?', 'Good evening, boss! I brought snacks and fear!',
      'Evening, boss! Is it overtime or a hobby?', 'Boss, the moon is out! So are my eye bags!', 'Good evening! Let’s make some questionable decisions!',
      'Boss! The night shift reports for glory!', 'Evening, boss! My bed is crying, but I’m here!', 'Hi boss! Please say the deadline is tomorrow!',
      'Evening, boss! Let’s code like nobody’s watching!',
    ],
    HELLO_BOSS: [
      'Boss! My hero! My captain! My caffeine supplier!', 'Hello, boss! I swear I wasn’t late. Time was early!', 'Boss, I’m here! You can stop worrying now!',
      'Greetings, boss! Please look at how busy I am!', 'Boss! You’re in! The office feels complete!', 'Hi, boss! I came in through sheer willpower!',
      'Reporting in, boss! Armed and mildly caffeinated!', 'Boss! Tell me what to do, I’m ready! Probably!', 'Oh, hello boss! Fancy meeting you here!',
      'Boss, I’m present! Please note it in the record!', 'Morning, noon or night, boss, I’m yours!', 'Boss! I brought my A game! Okay, my B game!',
      'Salutations, boss! May your builds be green!',
    ],
    HELLO_BOSS_TEAM: [
      'Hello, boss and the legendary team!', 'Everyone’s here! It’s like a boy band reunion!', 'Boss, team! Don’t stop, you look so productive!',
      'The gang’s all here! Who’s got the snacks?', 'Greetings, boss and crew! I’m here to complicate things!', 'Hi, everybody! Did I miss the drama?',
      'Boss! Team! What are we conquering today?', 'Hello, my favourite people in this room! All of you!', 'I’m in! Please clap! Quietly, my head hurts!',
      'Boss, team, hi! Let’s do something heroic!',
    ],
    BYE_DIRECTOR: [
      'Lights off, doors locked, legend retired!', 'Goodnight, office! Don’t burn down without me!', 'The last one out turns the lights off. That’s me!',
      'Farewell, desk! I shall return, probably late!', 'Locking up! If you hear a noise, it’s the cat!', 'The day is done and so am I!',
      'Mission accomplished! Or at least survived!', 'Goodnight, plants! Please grow while I sleep!', 'Out I go! The building is yours, ghosts!',
      'I’m leaving! Tell my keyboard I’ll miss it!', 'Bye, office! You were chaos, as always!', 'Switching off everything but my dreams!',
      'Home time! My sofa has waited long enough!', 'Closing the office! Nobody panic, I took the keys!', 'And the legend vanishes into the night!',
      'Goodnight, Wi-Fi! Be kind to tomorrow!',
    ],
    BYE_BOSS: [
      'Bye, boss! Please don’t break anything without me!', 'Heading out, boss! My bed is calling at full volume!', 'Boss, I’m off! Do try to go home eventually!',
      'Goodnight, boss! Remember, sleep is also a feature!', 'I’m leaving, boss! It’s not you, it’s the clock!', 'See you tomorrow, boss! If I survive the commute!',
      'Bye boss! Don’t let the bugs bite!', 'Out I go, boss! I left my chair warm for you!', 'Farewell, boss! Tell the deadlines I said hi!',
      'Boss, I’m gone! Text me if the server explodes! Or don’t!', 'Goodnight, boss! May your merges never conflict!', 'I’m outta here, boss! Dinner is a priority!',
      'Take care, boss! Water the plants, and yourself!', 'Boss, I’m heading home! Have fun being brave!', 'Bye, boss! I’m off to forget everything!',
      'Cheerio, boss! The couch and I have an appointment!',
    ],
    BYE_BOSS_TEAM: [
      'Goodnight, everyone! Try to survive without me!', 'Bye, boss! Bye, team! Don’t miss me too much!', 'I’m off, comrades! Hold the line!',
      'See you all tomorrow! Or in my dreams, haunting!', 'Farewell, team! Boss, you’re in charge of fun!', 'Bye all! Don’t touch my snacks!',
      'Home time! Boss, team, you’re all heroes!', 'Out! Save some work for tomorrow, folks!', 'Night, boss! Night, team! Be dramatic without me!',
      'The shift is over! Hugs for the boss, high-fives for all!', 'I’m heading out! Somebody say something nice about me!',
    ],
    ACK: [
      'A new request! Alert the media!', 'Oh, you want something? How thrilling!', 'Say no more! I’m already panicking productively!',
      'Message received! My brain is cracking its knuckles!', 'On it! With the power of a thousand coffees!', 'Challenge accepted! Please don’t look at my face!',
      'Consider it done! Or at least started dramatically!', 'Yes, yes, yes! Right away, grand master!', 'A mission! My favourite kind of trouble!',
      'I’m on it like a cat on a warm laptop!', 'Request spotted! Unleashing the minions!', 'Hold my coffee, I’m diving in!',
      'Wow, a task! Such honour! Such deadline!', 'Got it! I’ll treat it like a national emergency!', 'The user has spoken! Tremble, tasks!',
      'Understood! Time to look very serious!', 'Right! Operation Do-The-Thing begins now!', 'Leave it with me! I make no promises, but plenty of noise!',
      'A new quest appears! Dramatic zoom!', 'I heard you! The whole office heard you!', 'Message received, spirit lifted, sleeves rolled!',
      'You ask, I panic, then I deliver!', 'On it, chief! Please clear the runway!', 'Oh, a favour! I live for these!',
      'Noted in blood and sticky notes!', 'Right away! I just need one small crisis first!', 'Roger that! Engines roaring, noodles pausing!',
      'My inbox sings with joy! Let’s go!', 'Tasks assigned, destiny awakened!', 'Finally, some work! I was getting bored of my own jokes!',
      'Consider me summoned! Details to follow, drama included!', 'I’m on the case! The case is terrified!', 'Understood! Calling in every staff member!',
      'Sure thing! Let me just crack the mighty plan!', 'Boom! Request received, adrenaline served!',
    ],
    ACK_CALL: [
      'Phone call? Dramatic! Noted every word!', 'Got it over the phone! My ear is still ringing!', 'Heard you loud and clear! Mostly clear!',
      'Call received, message decoded, panic initiated!', 'Well, that was a plot twist! On it!', 'I’ll do it! Thanks for the telephone drama!',
      'Hanging up and diving in!', 'Noted! Writing it down before I forget my own name!', 'That call gave me wings! Tiny, nervous wings!',
      'Okay okay okay! Starting right now!', 'Message decoded! Sending in the troops!', 'Phone down, sleeves up! Let’s go!',
      'Consider it handled! Please stop ringing!', 'Understood! My phone is a hero today!', 'I got it! Even the bit I didn’t hear!',
    ],
    REPORT_OK: [
      'Boss! It’s done! Fireworks, please!', 'Behold! A task completed with only mild tears!', 'Mission accomplished! Tell my mother!',
      'Finished! I’d like my statue now, thanks!', 'All done, boss! I earned this noodle break!', 'Here’s the report! It’s beautiful! Weep!',
      'I did it! And nothing exploded! Yet!', 'Task complete! I need a nap and a trophy!', 'Boss, I came, I coded, I conquered!',
      'Done! Please admire it from a respectful distance!', 'Report delivered! Shall we dance?', 'It’s finished! I’m a legend! A tired legend!',
      'Success, boss! Cue the confetti cannon!', 'Everything went well! I’m as shocked as you are!', 'Handing it in! Please don’t find typos!',
      'Done and dusted! Mostly dusted!', 'Boss! Greatness has been achieved!', 'Boss, it works! Please don’t ask me how!',
      'The task is complete! The cat approves!',
    ],
    REPORT_FAIL: [
      'Boss, it broke! It broke spectacularly!', 'The task failed, but it went down fighting!', 'Disaster, boss! A small, manageable disaster!',
      'It didn’t work! I’m blaming Mercury retrograde!', 'Report: smoke, tears, zero success!', 'I failed! Gloriously! Tragically!',
      'Boss, the code has betrayed me!', 'Not my fault! Okay, maybe a little my fault!', 'It exploded, boss! Not literally! Mostly!',
      'The mission has gone sideways! Cue sad trombone!', 'I tried, boss! The universe disagreed!', 'It’s broken! I have no words, only sobs!',
      'Failure! But, hey, I learned something! Pain!', 'Boss, we have a situation! A big, juicy situation!', 'I lost the battle but not the war!',
      'Please don’t shout! The bug shouted first!', 'It failed! I demand a funeral and a sandwich!',
    ],
    DONE_OK: [
      'All done! Somebody call the newspapers!', 'The whole thing is finished! I’m weeping with joy!', 'Victory! Glorious, noisy victory!',
      'Everything is done! Tell my fans!', 'Mission complete! I deserve a parade!', 'It’s over! And nobody died! Great success!',
      'We did it! Cue the confetti, fetch the cake!', 'Done! I want a medal made of noodles!', 'Finished! The cat is so proud!',
      'The session is complete! Bow, everyone, bow!', 'Everything shipped! Where’s my crown?', 'All tasks green! I might cry!',
      'Done and done! The universe is in order!', 'Work complete! Sound the trumpets of triumph!', 'That’s a wrap! Please hold your applause!',
      'Success! Let the legends be written!', 'Finished! My keyboard needs a vacation!', 'All clear! No bugs were harmed! Mostly!',
      'It’s done! I feel like a god. A tired god!', 'Hallelujah! The job is done!', 'We crushed it! Someone fetch the brass band!',
      'Everything works! I’m as shocked as you are!', 'Total victory! Tell the Wi-Fi it can rest!', 'Done! Now the real work: lunch!',
      'The mission is complete! Roll the credits!', 'All finished! My brain has left the building!', 'Great news, everybody! Nothing’s on fire!',
      'Triumph! Pure, caffeinated triumph!', 'The work is done! Tell the deadlines to go home!', 'We’re finished! Somebody hug me!',
      'Everything is complete! Frame this moment!', 'Ta-da! The entire thing, done!', 'Epic win! Write it in the history books!',
      'Done! My coffee has outlived the project!', 'Wrapped up! Everybody get a cookie!', 'We shipped! Dance! Dance now!',
      'Perfect run! I’m framing the log!', 'Session complete! Let the legends nap!', 'The last task is done! I’m free! Free!',
      'It’s all finished! Mondays can’t stop us!', 'Done! I’d like my cape now, please!', 'Success all around! The cat purrs in approval!',
      'All done! Bring me noodles and glory!', 'Finished! Time to pretend this was easy!',
    ],
    DONE_FAILED: [
      'It’s finished, but some parts exploded!', 'Done! With a few casualties!', 'The work ended and a few tasks cried!',
      'Wrapped up, but there’s a mess! A funny mess!', 'Finished! Some tasks failed, so please don’t look!', 'Mission over! Partial glory, partial tears!',
      'It’s done! Mostly! Okay, sort of!', 'The session ended in drama! Check the paper!', 'Not perfect, but still standing! Barely!',
      'Some tasks went down in flames! Salute!', 'Complete, with some spectacular failures!', 'It’s over! A few bugs are still laughing!',
      'We finished! A few things didn’t! Oops!', 'The run ended! Some red marks on the report!', 'Done, with a side of disaster!',
      'Finished! The failures are very dramatic, see below!',
    ],
    DONE_BIG: [
      'A monster of a session, and it’s finished!', 'That was huge! My fingers have retired!', 'An epic marathon is over! I need a week off!',
      'The giant run is done! Somebody carry me!', 'Gigantic work, completed! Fetch my crown!', 'It was a beast, and we slayed it!',
      'So many tasks! I lost count! And my mind!', 'What a monstrous run! Tell the bards!', 'The mountain is climbed! I’m exhausted!',
      'Massive! Colossal! And done! Wow!', 'That took forever and I loved every second! Lies!', 'A legendary run is complete!',
      'It was a titanic job! Please bring snacks!', 'Endless tasks, endless glory! All done!',
    ],
    DONE_HINT: [
      'The summary is on my desk! Go on, read it!', 'Details on the paper! I wrote it with love!', 'Everything’s on the sheet by my desk! Dramatic reading optional!',
      'Check the paper on my desk! It’s a masterpiece!', 'The full story is on the desk! Gasp responsibly!', 'My desk has the summary! Don’t spill coffee on it!',
      'Peek at the paper! It’s juicy!', 'The whole saga is written on my desk!', 'Look at the summary sheet! It’s very official!',
      'Read the paper on the desk! There’s a plot twist!', 'All the details are on the desk paper! Go! Go!', 'The report awaits on my desk! Brace yourself!',
    ],
  },
  named: {
    HELLO_MATE_MORNING: [
      '{n}! You’re awake?! A miracle of the morning!', 'Morning, {n}! You look like a sleepy panda!', '{n}! Is that coffee in your hand? Share!',
      'Good morning, {n}! Did the alarm clock lose again?', '{n}! Bright and early! Who are you and what did you do with them?',
      'Morning, {n}! Please don’t talk to me before coffee! I mean, hi!', '{n}, you made it! The sun is jealous!',
    ],
    HELLO_MATE_AFTERNOON: [
      '{n}! You’re alive! Lunch didn’t eat you!', 'Afternoon, {n}! Did you nap or did you vanish?', '{n}! The afternoon hero! Very fashionably late!',
      'Hi {n}! Still digesting? Me too!', '{n}! You came back from lunch! Brave soul!', 'Afternoon, {n}! Save me from this slump!',
      '{n}! Tell me you brought dessert!',
    ],
    HELLO_MATE_EVENING: [
      '{n}! Working at night? You’re my hero!', 'Evening, {n}! The moon says hi!', '{n}! Late shift buddy! Let’s suffer together!',
      'Hi {n}! Don’t you have a home? I do. I’m ignoring it!', '{n}! The night owls unite!', 'Evening, {n}! Pass me the snacks of sorrow!',
      '{n}! You’re here too? We’re doomed! Or heroic!',
    ],
    HELLO_MATE_ANY: [
      '{n}! Long time no see! Ten minutes, an eternity!', 'Oh, {n}! My favourite human in this room!', '{n}! Please say you brought snacks!',
      'Hello {n}! Did you miss me? Don’t lie!', '{n}! Look who’s here! The legend itself!', 'Hey {n}! Let’s pretend we’re very busy!',
      '{n}! Great, now it’s a party!', 'Ah, {n}! The one person who laughs at my jokes!', '{n}! Welcome back to the circus!',
    ],
  },
};
