import type { PhraseExtra } from './phraseExtra';

export const MORE: PhraseExtra = {
  chatScripts: [
    ['I just got a merge conflict!', 'How big?', 'Forty files. And one cry for help.', 'Pick “accept both” and pray!'],
    ['Stack Overflow is down!!', 'Nooo! How will we code?!', 'I guess we… think?', 'Quick, call a doctor, I feel faint!'],
    ['I found the bug!!', 'Where was it?!', 'A missing comma. FOUR HOURS!', 'The comma wins again. Legend.'],
    ['The printer is jammed AGAIN!', 'Did you threaten it?', 'I offered it a hug!', 'It wants a sacrifice. Sorry, paper.'],
    ['Why is the fish staring at me?!', 'He knows what you did.', 'I only overfed him a little!', 'Ten pellets is not “a little”!'],
    ['My build takes ten minutes!', 'That’s a nap, friend!', 'I’ve had three naps today!', 'Efficiency king! Productivity prince!'],
    ['I mass-renamed a variable!', 'Everywhere?!', 'Even in the comments. And the poems.', 'Poems? Whose poems?! Show me!'],
    ['I wrote a TODO in 2021!', 'Still there?!', 'It has grown a little moss.', 'Museum piece! Put a rope around it!'],
    ['The AI said “great question”!', 'Aww, so sweet!', 'Then it wrote the wrong answer!', 'Charming AND wrong. A real coworker!'],
    ['I ran out of tokens!!', 'At lunchtime?!', 'I said “hello” and paid the price!', 'Hello is expensive these days. Tragic!'],
    ['I’m naming it “final_v2_REAL”.', 'What happened to v1?!', 'We don’t speak of v1!', 'Then “final_v3_REALLY” is next!'],
    ['What’s our uptime?', 'Ninety-nine percent!', 'Wow, that’s great!', 'The one percent is today. Hi!'],
    ['The standup took forty minutes!', 'Standing up?!', 'Half of us sat down in protest.', 'Revolution! Beanbags for everyone!'],
    ['Who touched the thermostat?!', 'Not me! I swear on the cat!', 'Then who made it Antarctica?!', 'The cat. She has paws. Case closed.'],
    ['I opened the logs.', 'And?!', 'They opened me back.', 'Staring into the abyss. Classic Tuesday!'],
    ['My laptop fan sounds like a jet!', 'Taking off?!', 'Yes! Nobody tell the passengers!', 'Please fasten your seat belts. Chrome is open.'],
    ['I have a brilliant idea!', 'Go on, go on!', 'We rewrite it all in Rust!', 'On a Thursday?! Sit down and breathe.'],
    ['I just killed a plant.', 'WHICH ONE?!', 'The cactus. By watering it.', 'The one thing that needs nothing! Wow!'],
    ['The coffee machine made a sound!', 'A happy sound?!', 'A “call my lawyer” sound!', 'Back away slowly. No sudden espressos.'],
    ['I wrote clean code today!', 'Show me! Show me!', 'It was so clean I deleted it.', 'Minimalism taken a TAD too far!'],
    ['Why is the sofa so comfy?!', 'It’s a trap!', 'A beautiful, fluffy trap!', 'Fifteen minutes. Set an alarm. You won’t.'],
    ['Daily reminder: it’s not a bug.', 'Then what is it?!', 'An unplanned surprise feature!', 'I’ll put that on the invoice!'],
    ['Our backlog has 900 tickets!', 'NINE HUNDRED?!', 'Some are older than the fish.', 'The fish is a founding member! Respect!'],
    ['I’ve been staring at this line forever.', 'What does it do?', 'It does… absolutely nothing!', 'Then delete it! Free the line!'],
    ['I tried to fix the typo!', 'And?!', 'Now there are three typos.', 'A typo family! Beautiful growth!'],
    ['Is that noodle smell yours?!', 'Guilty! Spicy edition!', 'My eyes are watering!', 'That’s not spice. That’s FLAVOUR.'],
    ['Somebody renamed the main branch!', 'To what?!', '“main-new-final-use-this”.', 'We’re doomed. Order flowers.'],
    ['I made a to-do list!', 'Wow, so organised!', 'Step one: make a to-do list.', 'Done! You may now nap triumphantly.'],
    ['The cat is in the server box!', 'Is it warm in there?!', 'It’s her new office!', 'Fine. But she pays rent in purrs.'],
    ['My keyboard has crumbs!', 'How many?', 'Enough to open a bakery!', 'Great! Start selling keyboard cookies!'],
    ['Do you read the changelog?', 'Never!', 'Me neither!', 'Then why did we write it? Dramatic pause.'],
    ['I got a thumbs-up on my review!', 'Congratulations!!', 'It was from the bot.', 'The bot has excellent taste! Cherish it!'],
    ['The meeting could’ve been an email!', 'The email could’ve been silence!', 'Silence could’ve been a nap!', 'NOW we’re talking!'],
    ['I think the monitor is judging me!', 'It has a crack.', 'It cracked from my code!', 'Brutal. Even the screen gave up.'],
    ['I fixed it with a comment!', 'A comment?!', '“Don’t touch this. Seriously.”', 'The strongest security known to humans.'],
    ['How do you spell “deprecated”?', 'D-E-P… oh no.', 'I’ve been writing it wrong for years!', 'Autocomplete has been protecting you. Thank it.'],
    ['I screamed at the compiler!', 'Did it help?!', 'It screamed back. In red!', 'At least somebody’s passionate here!'],
    ['I’m so tired of meetings!', 'Same! Want a break?', 'Yes! Let’s schedule one!', 'In a meeting. About breaks. Perfect!'],
    ['Why is the sun so bright?!', 'It’s a window, not a laser!', 'It’s hitting my monitor!', 'Behold: the nemesis of every developer!'],
    ['I upgraded my chair!', 'Is it comfy?!', 'I can’t get out of it!', 'Then it’s perfect! Roll to the kitchen!'],
    ['Do you test in production?', 'Only on special occasions!', 'Like what?!', 'Mondays. And whenever I’m brave.'],
    ['I gave the AI my whole repo!', 'And what did it say?!', '“Wow.” Just “wow.”', 'High praise! Or a cry for help.'],
    ['My mug says “Best Coder”!', 'Who gave you that?', 'I bought it myself!', 'Confidence! Maximum! I love it!'],
    ['Why is the Wi-Fi named “Free Cookies”?!', 'Did you connect?!', 'There were no cookies!', 'Scammed by a router. Welcome to the internet!'],
    ['I hid a bug under a feature flag!', 'Clever!', 'Now nobody can find the flag!', 'Perfect crime! The bug lives forever!'],
    ['The plant leaned toward my screen!', 'Aww, it’s a fan!', 'Or it’s reading my code!', 'Then it’s fleeing. Look, it’s turning away!'],
    ['I wrote the docs!', 'REALLY?! When?!', 'In my dreams. Last night.', 'Wake up and type them! Chop-chop!'],
    ['I got 200 unread emails!', 'Yikes! Reading them?', 'Declaring bankruptcy! Select all, delete!', 'Inbox zero! Freedom! Sweet silence!'],
    ['I brought a plant for the desk!', 'Cute! Name?!', 'Kevin. He’s a succulent.', 'Succulent Kevin! Great at deadlines: none!'],
    ['Why does the code smell weird?', 'Smell?!', 'It’s a code smell!', 'Open a window! Open ALL the windows!'],
    ['I almost deployed to the wrong server!', 'Almost?!', 'The cat stepped on Escape!', 'Promote her! She’s head of safety!'],
    ['My focus time is sacred!', 'Since when?', 'Since I put on headphones!', 'And they’re not even plugged in! Genius!'],
    ['I tripped over a cable!', 'Which one?', 'The one holding the internet!', 'You mean the one holding the fish tank?!'],
    ['Why is my code so long?!', 'Is it a poem?', 'It’s a novel! With chapters!', 'Add a plot twist: delete half of it!'],
    ['Where did the hours go?!', 'Into that one bug!', 'It ate my afternoon!', 'Greedy bug! Demand a refund!'],
    ['I just learned a shortcut!', 'Ooh, which one?', 'Ctrl+Z! After eight years!', 'Welcome to the future! Time is reversible!'],
    ['I trust the tests completely!', 'Good! They’re green!', 'Because I turned them off.', 'Trust issues solved! Brilliant!'],
    ['Somebody ate my yogurt!', 'Was your name on it?!', 'In BIG letters! With a skull!', 'The cat can’t read, so… suspect everyone!'],
    ['I’m a ten-times developer!', 'Wow! Really?', 'Ten times the coffee, ten times the bugs!', 'Impressive maths! Terrifying conclusions!'],
    ['The server room is freezing!', 'So are my toes!', 'The cat is happy though.', 'She loves a fridge with a Wi-Fi!'],
    ['I made a loading screen!', 'Fancy! How long?', 'Longer than the actual page!', 'Art takes time! So does disappointment.'],
    ['I just googled my own error!', 'And?!', 'The top answer was by me.', 'Past you is mocking present you! Cruel!'],
    ['Do we have a style guide?', 'We have a vibe guide!', 'What does it say?', 'Page one: “be nice to the cat”.'],
    ['I merged without looking!', 'You absolute daredevil!', 'It was one tiny change!', 'Those are the ones with fangs!'],
    ['I’ve been promoted!', 'To what?!', 'Chair holder of the sofa committee!', 'Great responsibility! Great cushions!'],
    ['Look, my screen is on fire!', 'Where?! WHERE?!', 'It’s the dark theme, calm down.', 'My heart! My poor heart! Warn me!'],
    ['I’m going to learn a new language!', 'Which one?!', 'English. Properly. Eventually.', 'Ambitious! Start with “semicolon”!'],
    ['This sprint is cursed!', 'Why?!', 'Three people got sick, two laptops died.', 'And the fish looks suspicious. Burn sage!'],
    ['I wrote a haiku in the commit.', 'Read it! Read it!', '“Fixed bug. Found more bugs. Sigh.”', 'Five-seven-five? No. But still art!'],
    ['I’m the fastest typist here!', 'Prove it!', 'Watch! … Oh, wrong window.', 'Speed with zero accuracy! Iconic!'],
    ['Why is everyone so quiet?', 'The deploy is running!', 'Everybody’s holding their breath?!', 'Turn blue! Nobody breathe until it’s green!'],
    ['I made noodles for the team!', 'AWESOME! How many?!', 'One bowl. For me. Team, you’re next.', 'Stolen hope! My hopes! My dreams!'],
    ['Check the logs, they’re beautiful!', 'Why?!', 'Eighty thousand lines of “undefined”!', 'A masterpiece of emptiness!'],
    ['I got locked out of my own laptop!', 'Forgot the password?!', 'I changed it to something “unforgettable”.', 'And now it’s forever forgotten. Poetry!'],
    ['Pizza arrived! Who ordered?!', 'Not me!', 'Not me either!', 'Then it’s free! Run! Run! RUN!'],
    ['I can fix it in five minutes!', 'Famous words!', 'This time I’m serious!', 'See you at midnight, hero!'],
    ['Was that thunder?!', 'No, my stomach!', 'Stomach thunder! Snack alert!', 'Biscuits! Quick! Before the storm!'],
    ['Who put sticky notes on my screen?!', 'Reminders!', 'My screen looks like a yellow forest!', 'Look, one says “look behind you”!'],
    ['I’m about to touch legacy code!', 'Be brave, soldier!', 'Wish me luck! Tell my mum!', 'I’ll water your plant. And your fish.'],
    ['I’m writing a very short function.', 'How short?!', 'Three lines! Three!', 'Hold the phone! Call the newspapers!'],
    ['I ate lunch at my desk again!', 'Brave! What’s in the keyboard?', 'Rice. Possibly noodles. Mystery.', 'Archaeologists will study it someday!'],
    ['I just muted the whole meeting!', 'Nobody noticed?!', 'I was the speaker!', 'Silence! The most efficient talk ever!'],
    ['The fridge is empty! EMPTY!', 'Who took the snacks?!', 'Probably the same ghost as the yogurt!', 'Add a camera! Naming the ghost Gary!'],
    ['I found an old branch from 2018!', 'Is it alive?!', 'It’s feral! It bites!', 'Burn it! Or give it a name. Hard call.'],
    ['I just remembered the deadline!', 'When is it?!', 'Yesterday! Maybe the day before!', 'Time is a flat circle. Or a wall.'],
    ['What’s the best thing about Fridays?', 'Wearing slippers!', 'And leaving before the pager rings!', 'It’s ringing. Hide in the beanbag!'],
    ['My code is self-documenting!', 'Where’s the proof?!', 'It’s so confusing, nobody dares ask.', 'The finest form of security. Bravo!'],
    ['I’m going to focus for one hour!', 'Dramatic! Phone away?', 'Phone away! Door shut! Lights low!', 'Cat on lap. Focus level: gone.'],
    ['Why is my screen full of tabs?!', 'Did you count them?', 'I counted to thirty, then I ran.', 'Close them all! Fresh start! Brave soul!'],
    ['The coffee tastes like regret today!', 'Tangy?!', 'Deep, dark, slightly burnt.', 'Like my last pull request. Bottoms up!'],
  ],
};
